#version 450
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_GOOGLE_include_directive : enable

//--------------------------------------------------------------------------------------
// includes
//--------------------------------------------------------------------------------------
#include "core/core.glsl"

//--------------------------------------------------------------------------------------
// work group local size
//--------------------------------------------------------------------------------------
layout(local_size_x = 32) in;
layout(local_size_y = 32) in;

//--------------------------------------------------------------------------------------
// resources
//--------------------------------------------------------------------------------------
layout(set = 3, binding = 0, rgba16f) readonly uniform image2D _source;
layout(set = 3, binding = 1, rgba16f) writeonly uniform image2D _target;

//--------------------------------------------------------------------------------------
// program
//--------------------------------------------------------------------------------------
void main() {
    // Get the global invocation ID
    const ivec2 id = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);

    ivec2 sourceCoords = id * 2;

    vec4 sampleSum = vec4(0.0);
    for (int i = 0; i < 2; ++i) {
        for (int j = 0; j < 2; ++j) {
            ivec2 offset = ivec2(i, j);
            const vec4 s = imageLoad(_source, sourceCoords);
            sampleSum += s;
        }
    }

    vec4 averagedSample = sampleSum / 4;

    imageStore(_target, id, averagedSample);
}